---
- name: Collect log files from Control Node
  hosts: control_node
  gather_facts: no

  tasks:
    - name: Gather log files
      fetch:
        src: /var/log/
        dest: ~/hoa7/logs.txt
        flat: yes
