---
- name: Collect log files from Control Node
  hosts: control_node
  gather_facts: no
  tasks:
    - name: Fetch log files from Control Node
      ansible.builtin.find:
        paths: /var/log
        file_type: file
      register: log_files

    - name: Fetch each log file
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: ~/hoa7/logs
        flat: yes
      with_items: "{{ log_files.files }}"

- name: Show collected logs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display collected logs
      debug:
        msg: "Logs collected from Control Node and stored in ~/hoa7/logs directory"
